In [6]:
import numpy as np
matriz = np.array([[2, 3, 1],
[4, 5, 7]])

matriz


array([[2, 3, 1],
       [4, 5, 7]])

In [ ]:
matriz[0]

In [12]:
matriz[0][2]

np.int64(1)

In [14]:
matriz[1][2]

np.int64(7)

In [19]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
